use_frameworks!

platform :ios, '8.0'

target 'MSKit_Example' do
  pod 'MSKit', :path => '../'

  target 'MSKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
